#!/usr/bin/env bash
#script to print the clock
hour=0
count=0

while [ $hour -lt 12 ] && [ $count -lt 70 ]; do
  echo "Hour: $hour"
  minute=1
  while [ $minute -lt 60 ] && [ $count -lt 70 ]; do
    echo $minute
    minute=$((minute + 1))
    count=$((count + 1))
  done
  hour=$((hour + 1))
done
