#!/usr/bin/env bash
#Script to change localhost and facebook IP
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

echo -e "$localhost_ip\tlocalhost" >> /etc/hosts
echo -e "$facebook_ip\tfacebook.com" >> /etc/hosts

